# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/test-results.xml'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'

- script: |
    rm -rf node_modules
    rm package-lock.json
    npm install --only=dev
    npm install -g gulp
    npm install -g rimraf
  displayName: 'npm install'
- script: |
    npm run clean
  displayName: 'Clean Lib directory'
- script: |
    npm run build
  displayName: 'Build project'
- script: |
    npm test
  displayName: 'Run Unit Tests'
- script: |
    npm run copy
  displayName: 'Copy artefacts'
- script: npm publish
  displayName: 'Publish to NPM registry'
