version: '3.1'

services:
  app:
    build: .
    command: npm run build
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app/oauth2-api
      - /home/app/oauth2-api/node_modules
